## [START cloudbuild_basic_config]
#steps:
#  # Docker Build
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t',
#           'us-central1-docker.pkg.dev/klara-comm-nonprod/springboot-registry/my-klara-app:${SHORT_SHA}',
#           '.']
#
#  # Docker Push
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push',
#           'us-central1-docker.pkg.dev/klara-comm-nonprod/springboot-registry/my-klara-app:${SHORT_SHA}']
#
#  #Store images in google artifact registory
#images:
#  - us-central1-docker.pkg.dev/klara-comm-nonprod/springboot-registry/my-klara-app:${SHORT_SHA}
#
## Build logs bucket
#  - name: 'gs://klara-comm-nonprod.appspot.com'
#
#options:
#  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
#  logging: CLOUD_LOGGING_ONLY
## [END cloudbuild_basic_config]

steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/klara-comm-nonprod/github.com/parthavdevs198/springboot-docker-app:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/klara-comm-nonprod/github.com/parthavdevs198/springboot-docker-app:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo-app'
      - '--image'
      - 'gcr.io/klara-comm-nonprod/github.com/parthavdevs198/springboot-docker-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/klara-comm-nonprod/github.com/parthavdevs198/springboot-docker-app:$COMMIT_SHA'